apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "railpulse.fullname" . }}
  labels:
    app.kubernetes.io/name: railpulse
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: railpulse
  template:
    metadata:
      labels:
        app: railpulse
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: railpulse
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: OPERATOR_PIN
              value: "{{ .Values.env.OPERATOR_PIN }}"
            - name: NODE_ENV
              value: "{{ .Values.env.NODE_ENV }}"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
